ALTER TABLE `users`
    ADD COLUMN IF NOT EXISTS `health` TINYINT UNSIGNED NOT NULL DEFAULT 100 AFTER `credits`,
    ADD COLUMN IF NOT EXISTS `stamina` TINYINT UNSIGNED NOT NULL DEFAULT 100 AFTER `health`;
